# Generated by Django 4.2.30 on 2026-09-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('intensidad_horaria', models.PositiveIntegerField(help_text='En horas')),
                ('instructor', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Completado', 'Completado')], default='Activo', max_length=20)),
            ],
        ),
    ]
